import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/layout/LeftSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <div className="flex flex-col xl:flex-row min-h-screen relative">
          {/* left sidebar - fixed on large screens */}
          <div className="w-full xl:w-140 xl:fixed xl:top-0 xl:left-0 xl:h-screen bg-blue-200 overflow-y-auto z-20">
            <LeftSidebar />
          </div>
          {/* main content – offset on large screens */}
          <div className="flex-1 xl:ml-140 bg-stone-100">{children}</div>
        </div>
      </body>
    </html>
  );
}
